"""
Bootstrap a real browser session so captcha_encoded is generated by site JS.

Synthetic fingerprint encryption is rejected by the server. A short Playwright
session produces a valid captcha_encoded + cookies; OCR/submit can stay on requests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .captcha import DEFAULT_USER_AGENT


@dataclass(slots=True)
class BrowserCaptchaChallenge:
    image_bytes: bytes
    captcha_encoded: str
    cookies: dict[str, str]
    user_agent: str
    image_src: str = ""
    captcha_token: Optional[str] = None


def fetch_browser_challenge(
    *,
    user_agent: str = DEFAULT_USER_AGENT,
    headless: bool = True,
    wait_ms: int = 5000,
    timeout_ms: int = 90000,
) -> BrowserCaptchaChallenge:
    """
    Open zefoy.com in Chromium, wait for captcha image + captcha_encoded.

    Requires: pip install playwright && playwright install chromium
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise RuntimeError(
            "Playwright is required for captcha submit. "
            "Install: pip install playwright && playwright install chromium"
        ) from exc

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=headless)
        context = browser.new_context(
            user_agent=user_agent,
            viewport={"width": 1366, "height": 768},
            locale="en-US",
        )
        context.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        )
        page = context.new_page()
        image_holder: dict[str, Optional[bytes]] = {"b": None}

        def on_response(res) -> None:
            try:
                if "_CAPTCHA=" in res.url and res.status == 200:
                    image_holder["b"] = res.body()
            except Exception:
                pass

        page.on("response", on_response)
        page.goto("https://zefoy.com/", wait_until="domcontentloaded", timeout=timeout_ms)
        page.wait_for_timeout(wait_ms)

        enc = ""
        src = ""
        for _ in range(50):
            try:
                enc = page.input_value("#captchaencoded") or ""
            except Exception:
                enc = ""
            try:
                src = page.get_attribute("#captcha-img", "src") or ""
            except Exception:
                src = ""
            if enc and len(enc) > 50 and (image_holder["b"] or src):
                break
            page.wait_for_timeout(200)

        if not enc or len(enc) < 50:
            browser.close()
            raise RuntimeError("captcha_encoded was not generated by the page JS")

        img = image_holder["b"]
        if not img and src:
            arr = page.evaluate(
                """async (src) => {
                    const r = await fetch(src);
                    const b = await r.arrayBuffer();
                    return Array.from(new Uint8Array(b));
                }""",
                src,
            )
            img = bytes(arr)

        if not img:
            browser.close()
            raise RuntimeError("Captcha image was not loaded")

        token = None
        if "_CAPTCHA=" in src:
            token = src.split("_CAPTCHA=", 1)[1].split("&", 1)[0]

        cookies = {c["name"]: c["value"] for c in context.cookies()}
        browser.close()

        return BrowserCaptchaChallenge(
            image_bytes=img,
            captcha_encoded=enc,
            cookies=cookies,
            user_agent=user_agent,
            image_src=src,
            captcha_token=token,
        )
